[Numpy site](https://numpy.org/)

<!-- ![numpy_vec](https://mblogthumb-phinf.pstatic.net/MjAyMTEwMDZfMTQz/MDAxNjMzNTA3ODg4MDI0.TK4Ec09t6G0wuT1fe_Utg_8cCwm_qsnycmMqq1K90V4g.bAeGD3GjsZcICBwQD0q6cFUtFlz9fXiOhH4eyVO7IUsg.JPEG.swedu_et/What-is-NumPy-in-Python.jpg?type=w800) -->

<img src='https://mblogthumb-phinf.pstatic.net/MjAyMTEwMDZfMTQz/MDAxNjMzNTA3ODg4MDI0.TK4Ec09t6G0wuT1fe_Utg_8cCwm_qsnycmMqq1K90V4g.bAeGD3GjsZcICBwQD0q6cFUtFlz9fXiOhH4eyVO7IUsg.JPEG.swedu_et/What-is-NumPy-in-Python.jpg?type=w800' width='800'>

* 이것은
* 넘파이
* 실습입니다

# Numpy tutorial

In [1]:
score = [12, 34, 56]

In [2]:
# score_new = []

In [3]:
# for s in score:
#     s = s + 3
#     score_new.append(s)

In [4]:
# score_new

In [5]:
for i, s in enumerate(score):
    score[i] = s + 3

In [6]:
score

[15, 37, 59]

In [7]:
!pip install numpy

In [8]:
import numpy as np

np.__version__

'1.23.1'

In [9]:
a = [1]
type(a)

list

In [10]:
x = (10,)
type(x)

tuple

## ndarray 클래스

In [11]:
xarr = np.array([23, 45, 56, 76])
print(xarr)
xarr

[23 45 56 76]


array([23, 45, 56, 76])

In [12]:
type(xarr)

numpy.ndarray

In [13]:
xarr.shape

(4,)

In [14]:
type(xarr.shape)

tuple

In [15]:
xarr.dtype

# int32, int64, float32, float64

dtype('int32')

In [16]:
xarr.size

4

In [17]:
xarr.itemsize

4

In [18]:
yarr = np.array([[10, 11],
                 [12, 13],
                 [15, 16]])
yarr.shape

(3, 2)

In [19]:
yarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]],
                 [[9, 10], [11, 12]]])
yarr.shape

(3, 2, 2)

In [20]:
yarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [21]:
yarr.dtype

dtype('int32')

In [22]:
type(yarr)

numpy.ndarray

In [23]:
yarr.astype('float32')

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)

In [24]:
yarr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [25]:
yarr = yarr.astype('float32')

In [26]:
yarr

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)

In [27]:
xarr = np.array([23, 45, 56, 76], dtype='float64')

In [28]:
xarr.dtype

dtype('float64')

In [29]:
yarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]],
                 [[9, 10], [11, 12]]])
yarr.shape

(3, 2, 2)

In [30]:
yarr.dtype

dtype('int32')

In [31]:
yarr = yarr.reshape(1, 3, 2, 2)

In [32]:
yarr.shape

(1, 3, 2, 2)

In [33]:
yarr

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

In [34]:
yarr = yarr.reshape(3, 2, 2)

In [35]:
yarr.shape

(3, 2, 2)

In [36]:
yarr = yarr.reshape(-1, 3, 2, 2)

In [37]:
yarr.shape

(1, 3, 2, 2)

In [38]:
yarr.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
yarr = yarr.reshape(-1, 2, 2)

In [40]:
yarr.shape

(3, 2, 2)

In [41]:
yarr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
yarr.shape

(3, 2, 2)

In [46]:
yarr[np.newaxis, :].shape

(1, 3, 2, 2)

#### np.arange()

In [47]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [52]:
xarr = np.arange(10).reshape(5,2)

In [53]:
xarr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [56]:
np.full((2, 3), 0)

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.zeros_like(yarr)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [59]:
np.ones_like(yarr)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

### random

In [64]:
np.random.uniform(0, 10, 5)

array([7.8092658 , 4.2927132 , 4.78937156, 9.87996498, 1.03242953])

In [65]:
np.random.normal(0, 1, 10)

array([-0.22600925, -1.47024963, -0.56739478, -0.07760781, -1.10752378,
       -0.62659953, -0.10904208,  0.49804083, -0.24496876,  0.3457999 ])

In [66]:
np.random.randn(10)

array([-1.35407869,  0.37640715, -1.68764642,  0.82449445, -0.33450441,
        0.01258602,  0.64994308,  0.46087157,  0.36945761, -0.19857905])

In [67]:
np.random.randn(2,3)

array([[0.23755549, 0.39945753, 0.57398594],
       [0.30699657, 0.41111378, 0.29692625]])

## 함수

In [70]:
xarr = np.arange(0, 12).reshape(3, 4)

In [71]:
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
xarr.sum()

66

In [75]:
xarr.sum(axis=0)

array([12, 15, 18, 21])

In [76]:
xarr.sum(axis=1)

array([ 6, 22, 38])

In [77]:
np.sum(xarr, axis=1)

array([ 6, 22, 38])

In [78]:
xarr.mean(axis=0)

array([4., 5., 6., 7.])

In [80]:
np.mean(xarr, axis=0)

array([4., 5., 6., 7.])

In [81]:
xarr.min(axis=0)

array([0, 1, 2, 3])

In [91]:
[1, 2, 3] + [3]

[1, 2, 3, 3]

In [92]:
xarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
xarr + 3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [90]:
xarr + [3, 2, 1, 1]

array([[ 3,  3,  3,  4],
       [ 7,  7,  7,  8],
       [11, 11, 11, 12]])

In [93]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[1, 2],
              [3, 4]])

In [94]:
x * y

array([[ 1,  4],
       [ 9, 16]])

In [95]:
x @ y

array([[ 7, 10],
       [15, 22]])

In [96]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])

In [97]:
np.dot(x, y)

14

In [98]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[1, 2],
              [3, 4]])

In [99]:
np.dot(x, y)

array([[ 7, 10],
       [15, 22]])

In [101]:
np.matmul(x, y)

array([[ 7, 10],
       [15, 22]])

In [104]:
x = np.array([1, 4, 3, 2])
x > 2

array([False,  True,  True, False])

In [105]:
x[[False,  True,  True, False]]

array([4, 3])

In [106]:
x[x > 2]

array([4, 3])

In [107]:
x[x > 2] = -1

In [108]:
x

array([ 1, -1, -1,  2])

In [130]:
x = [1, 2, 3]
y = [4, 5, 6]

In [131]:
np.concatenate((x, y), axis=0)

array([1, 2, 3, 4, 5, 6])

In [132]:
x = [[1, 2],
     [3, 4]]
y = [[5, 6],
     [7, 8]]

In [133]:
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [134]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [135]:
x = [1, 2, 3]
y = [4, 5, 6]

In [136]:
np.vstack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

In [137]:
np.hstack((x, y))

array([1, 2, 3, 4, 5, 6])

In [138]:
x = [[1, 2], [3, 4]]

In [139]:
x[1][0]

3

In [140]:
x = np.array([[1, 2], [3, 4]])

In [143]:
x[1, 0]

3

In [144]:
x[1][0]

3

## where

In [145]:
x = np.array([1, 2, 3, 4, 5])

In [146]:
x

array([1, 2, 3, 4, 5])

In [147]:
np.where(x > 3)

(array([3, 4], dtype=int64),)

In [148]:
np.where(x > 3, 1, 0)

array([0, 0, 0, 1, 1])

In [149]:
x = np.array([1, 2, 3, 4, 5, 6])

In [150]:
x

array([1, 2, 3, 4, 5, 6])

In [155]:
x_sub = np.where(x > 3, 1, 0)

In [156]:
x_sub.sum()

3

In [163]:
x = np.random.randn(4, 3)

In [164]:
x

array([[-0.48606017,  1.04444956, -0.20968539],
       [ 1.39984245,  0.29144837,  1.21502581],
       [-0.24792108,  1.42447066,  0.19222542],
       [ 1.01493868,  0.5754538 ,  2.43284866]])

In [165]:
np.argmax(x, axis=1)

array([1, 0, 1, 2], dtype=int64)

In [166]:
np.argmin(x, axis=1)

array([0, 1, 0, 1], dtype=int64)

In [167]:
xarr = np.array([1, 2, 3, 4, 5, 6, 7])

In [168]:
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [169]:
xarr[:-1]

array([1, 2, 3, 4, 5, 6])

In [171]:
xarr[-1]

7

In [173]:
y = xarr[3:5]

In [174]:
y

array([4, 5])

In [175]:
y[0] = -1

In [176]:
y

array([-1,  5])

In [177]:
xarr

array([ 1,  2,  3, -1,  5,  6,  7])

In [178]:
xarr = np.array([1, 2, 3, 4, 5, 6, 7])

In [179]:
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [180]:
y = xarr[3:5].copy()

In [181]:
y

array([4, 5])

In [182]:
y[0] = -1

In [183]:
y

array([-1,  5])

In [184]:
xarr

array([1, 2, 3, 4, 5, 6, 7])

In [190]:
iris = np.genfromtxt('./Dataset/iris.csv', delimiter=',', skip_header=1)

In [191]:
iris[:5]

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan]])

In [192]:
iris.shape

(150, 5)

In [193]:
iris.dtype

dtype('float64')

In [206]:
xarr = iris[:, :-1]

In [270]:
xarr.shape

(150, 4)

In [208]:
mean_col_1 = xarr[:, 0].mean()

In [217]:
mean_col_1

5.843333333333334

In [279]:
x = xarr[np.where(xarr[:, 0] > mean_col_1)]

In [280]:
y = xarr[np.where(xarr[:, 0] <= mean_col_1)]

In [285]:
x.shape

(70, 4)

In [286]:
y.shape

(80, 4)

In [287]:
x[:, 0].min()

5.9

In [288]:
x.shape

(70, 4)

In [289]:
y[:, 0].min()

4.3

In [290]:
y.shape

(80, 4)

In [291]:
np.savez('my_iris.npz', x=x, y=y)

In [293]:
my_iris = np.load('my_iris.npz')

In [294]:
type(my_iris)

numpy.lib.npyio.NpzFile

In [295]:
x = my_iris['x']

In [296]:
type(x)

numpy.ndarray

In [297]:
x.shape

(70, 4)

In [299]:
y = my_iris['y']

In [300]:
type(y)

numpy.ndarray

In [301]:
y.shape

(80, 4)